version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: test
    ports:
      - 5432:5432
    # volumes:
    # - ./*.sql:/docker-entrypoint-initdb.d/